sonar.projectKey=hotelier-laravel
sonar.projectName=Hotelier Laravel
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**,storage/**,bootstrap/**

sonar.host.url=http://localhost:9000
sonar.login=squ_d7abc431ec52ebd7df8dd6e1568f4e6c1e2a70c2
